### ISSUE TITLE
Report a bug in load_model_config function.

### ISSUE THREAD

**Issue by XiHuYan** [labomics/midas#3]
Line 225, run.py [link](https://github.com/labomics/midas/blob/b23feea0df8e13d1fa4a942c9e9b4feba3f24080/run.py#L225)

`o.dims_h[m] = dim if m != "atac" else o.dims_enc_chr[-1] * 22`

should be 

`o.dims_h[m] = dim if m != "atac" else o.dims_enc_chr[-1] * len(o.dims_chr)`

**Comment by wangjing-bio** [comment]
Thank you very much for your report. 
In fact, the experiments in our paper primarily focus on human PBMC and BMMC data. Since humans have only 23 pairs of chromosomes, and sex chromosomes can introduce batch effects between males and females, we simply split the input and reconstruction layers both into 22 independent layers (sex chromosomes were removed during data preprocessing). However, if there is a need to apply MIDAS to other species such as mice in the future, it would be convenient to replace 22 with len(o.dims_chr). 
Once again, thank you for your report!
