### ISSUE TITLE
 Inquiry Regarding Availability of MIDAS Software

### ISSUE THREAD

**Issue by adamtongji** [labomics/midas#5]
Thank you for your fantastic design of the MIDAS software for mosaic integration and imputation of single-cell multi-modal data.

Our team is conducting a registered study on multi-modal integration; however, we are unsure whether your MIDAS software has been released yet.

We hope for your quick reply, as it would greatly aid our study.

Thanks,

**Comment by wangjing-bio** [comment]
Thank you very much for your recognition and support for MIDAS. 
We are currently developing a more user-friendly version of the MIDAS software, but due to limited human resources, it will take some time to complete. In the meantime, we encourage you to use the code we have released on GitHub, following the provided instructions, to conduct your research. If you encounter any issues during your research, please feel free to reach out to us for assistance. 
Once again, we sincerely appreciate your recognition and support!

**Comment by adamtongji** [comment]
Thank you for your latest update of the user-friendly MIDAS software, tutorial and API documents!   
We encountered the following two questions regarding your software and tutorial:

- 1.  What is the difference among "batch correct", "imputation" and "translation" in your `scmidas.model.predict` function? Which one would be appropriate to be used for missing modality imputation? </br>
- 2. When we ran tutorial 1 CITE-seq integration, we failed to add `translate=True` to the `scmidas.model.predict` function (as screenshot below). Is it a bug or is the function unavailable for the tutorial 1 dataset? </br> 

<img width="1027" alt="截屏2024-07-11 14 57 50" src="https://github.com/labomics/midas/assets/13899771/1fae12a0-a561-4da9-9ffc-6a2d509915c7">

Thanks!

**Comment by JiahaoChow** [comment]
Thank you for trying our package!

i. Clarifications on "batch correction", "imputation", and "translation":

- "Batch correction" is discussed in our paper under the section "Batch correction via latent variable manipulation". Here, counts are generated from embeddings with "standard" technical noise, which might result in differences from the raw counts.

- "Imputation" is covered in the section 'Imputation for missing modalities and features' of our paper. It is implemented by encoding all observed data into embeddings and then generating counts for all modalities from the embeddings. Note that the generated counts are not batch-corrected.

- For "translation",  it encodes certain modalities into embeddings, then reconstructs other modalities from these embeddings. Note that the generated counts are not batch-corrected.

ii.  Please see #7 . Regarding the bug you encountered, it was due to the code trying to convert two modalities into a third, which is not applicable to the CITE-seq dataset that only contains two modalities. This issue has been resolved in the latest version (0.0.16) of scmidas. Please update to this version.

**Comment by adamtongji** [comment]
Thank you for your prompt reply and assistance. Your support enabled us to include the MIDAS software in our SCMMIB benchmark study (recently published online in *Nature Methods*) during the final week before submission. This ensured that we did not miss a top-performing tool for mosaic integration tasks and an impressively advanced method for cross-modality imputation, which matches—or even surpasses—the performance of supervised interpolation methods. 

Congratulations on MIDAS being recognized as a leading method in our evaluation！

**Comment by zhen-he** [comment]
Hello,

Thank you for your kind words and for including MIDAS in your comprehensive evaluation. We have read your paper and are thrilled that your work has highlighted the strengths of our method to the research community. We are committed to continuously improving MIDAS to make it even more user-friendly.

Congratulations on the publication of your benchmark study in _Nature Methods_!
